### ISSUE TITLE
Can we use Mesop with python 3.9?

### ISSUE THREAD

**Issue by kenki931128** [google/mesop#421]
**Describe the bug**
[PyPI](https://pypi.org/project/mesop/) said Mesop works with 3.9.
<img width="180" alt="Screenshot 2024-06-12 at 5 02 18 PM" src="https://github.com/google/mesop/assets/19543158/a2396db9-7483-492b-950b-7b80ab3f637d">

If I execute the demo code, it raises error `TypeError: dataclass() got an unexpected keyword argument 'kw_only'`, and arg `kw_only` in [dataclass](https://docs.python.org/3.10/library/dataclasses.html#module-contents) is available only >= 3.10. 

**To Reproduce**

1. Use python 3.9
2. Run `pip install mesop`
3. create main.py with [demo in README.md](https://github.com/google/mesop/blob/main/README.md#write-your-first-mesop-app-in-less-than-10-lines-of-code)
4. Run `mesop main.py`

**Expected behavior**
No error happens.

**Desktop System Info**

- OS: [macOS Sonoma Version 14.5]
- Python: [3.9.19]

**Additional context**
Please kindly let me know if 1) it only works with python >=3.10 or 2) there is any way to run with 3.9 / my mistake or 3) way to update the code.

**Comment by wwwillchen** [comment]
Thanks for the bug report! Yeah, we incorrectly labeled it as compatible with 3.9. I'll look into whether we can support 3.9 or we should just mark this package as >=3.10.

Out of curiosity, how difficult is it for you to upgrade Python versions?

**Comment by kenki931128** [comment]
@wwwillchen , thank you for your reply!
In my work, 3.9 is recommended unless there are special reasons. It is possible to upgrade the version to 3.10 but I'd be happy if it also works with 3.9!

**Comment by wwwillchen** [comment]
I looked into this and there's at least a couple things we'd need to change:

- Stop using kw_only for dataclass - this is somewhat tricky because if we don't force kw_only, then for some of our public API dataclass, especially `Style`, we would technically need to put new fields at the end in case people passed args positionally (I think this would be rare, but it's a consideration for maintaining backwards compatibility).
- Stop using `|` as a type union. You can use `Union[...]` which is just more verbose, but we have a lot of usages of type union so this is a bit tedious.

I looked at our stats (https://pypistats.org/packages/mesop) and so far <5% is using Python 3.9, so given the effort, I think we will only support 3.10+, but we can re-evaluate this if there's more demand.

For now, I'll update our pip package metadata so that it's not misleading.

I'll leave this issue open and if more people hit this issue, we'll re-consider.

**Comment by asma-faraji** [comment]
Hi 
I am trying to run the mesop app on Mac with python 3.11 and I am getting same error as reported . I would appreciate if you help me solving the bug.

**Comment by wwwillchen** [comment]
@asma-faraji - you shouldn't be hitting the error that OP [posted](https://github.com/google/mesop/issues/421#issue-2348236472) if you're running python 3.11 - could you paste the full error message that you're receiving? Also, can you double check that the Python version you're using is 3.10 or higher? (e.g. `python --version`). It's possible that you have multiple versions of Python on your system.

**Comment by wwwillchen** [comment]
Given that 3.9 is now 4 years old and will be retired next year, I don't think we'll get to this since the effort here is non-trivial.
